version: '3.8'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8

  app:
    build:
      context: .
      target: development #내가 추가함
      dockerfile: ./Dockerfile
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=test
      - DB_USERNAME=test
      - DB_PASSWORD=test
    depends_on:
      - db
    ports:
      - "8443:443"
    command:
        - bash
        - -c
        - |
          /app/wait-for-it.sh db:5432 -t 10
          npm run start:dev
        #   npm run elfactory_nestjs_api
    volumes:
      - ./:/app/